### ISSUE TITLE
Logo text

### ISSUE THREAD

**Issue by ivirshup** [PMBio/Muon.jl#9]
Just noticing a few issues with how the logo text in the docs (`svg` file)

## Logo has text embedded as \<text\>

![image](https://user-images.githubusercontent.com/8238804/146226974-3d87d64d-9640-44b1-b210-5ed1ca0e8eb1.png)

So it just defaults to browser font, since I don't have the specific font available. Probably worth exporting the text as shapes so it looks consistent.

## Text looks a bit funny in dark mode

![image](https://user-images.githubusercontent.com/8238804/146226733-afd35ba4-1bdf-40b2-9692-c3d567fcc48c.png)

Maybe documenter gives lets you specify an alternate for dark mode?

**Comment by ivirshup** [comment]
Should that have updated the hosted docs? Looks the same to me still

**Comment by gtca** [comment]
Thanks for checking!
I have checked now that running `julia --project=docs/ docs/make.jl` locally does generate documentation with new logos.

Is it a cache-related issue then?..

**Comment by ivirshup** [comment]
Uh, I think it may still be off. Here's what it looks like when I build the docs locally on my machine:

![image](https://user-images.githubusercontent.com/8238804/146405154-3895b9fe-f5da-40c0-9efb-b5b5f7805c03.png)

But the light mode version does look right:

![image](https://user-images.githubusercontent.com/8238804/146405075-df94532c-3bd3-47f7-973e-908fd6fb3345.png)
